### ISSUE TITLE
Error while uploading text file, downloader cant merge file -> error when opening file

### ISSUE THREAD

**Issue by NLPV2011** [plsgivemeachane/UFS#5]
![image](https://github.com/plsgivemeachane/UFS/assets/132674970/032d1852-cd30-40e2-b960-0092d6fcc3e3)
![image](https://github.com/plsgivemeachane/UFS/assets/132674970/ed2e1cb0-3c39-4245-91cc-6fcd40517d0b)
![image](https://github.com/plsgivemeachane/UFS/assets/132674970/d36d6869-c5e5-4076-95db-8d1ef5b04248)

**Comment by plsgivemeachane** [comment]
nice

**Comment by plsgivemeachane** [comment]
![image](https://github.com/user-attachments/assets/51db60a3-1a4d-46da-a7ab-c6dad90cc6a1)
At least for now I cannot fixed
